sudo: false
language: go
go:
- 1.9
- tip

matrix:
  allow_failures:
  - go: tip

before_install:
- openssl aes-256-cbc -K $encrypted_1867c6df6d6e_key -iv $encrypted_1867c6df6d6e_iv -in .travis.gae-deploy.json.enc -out .travis.gae-deploy.json -d

script:
- go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: gae
  verbosity: info
  keyfile: .travis.gae-deploy.json
  skip_cleanup: true
  project: ip-spuf-ru
  version: master
  default: true
  on:
    branch: master
    go: 1.9
