language: go
go:
- 1.6.2
- tip

before_install:
- openssl aes-256-cbc -K $encrypted_1867c6df6d6e_key -iv $encrypted_1867c6df6d6e_iv -in .travis.tar.enc -out .travis.tar -d
- tar xvf .travis.tar
- "[ -f $HOME/google-cloud-sdk/bin/gcloud ] || curl -L https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz | gzip -d | tar -x -C $HOME"
- $HOME/google-cloud-sdk/bin/bootstrapping/install.py --usage-reporting=false --command-completion=false --path-update=false
- go get -u golang.org/x/tools/cmd/cover
- go get -u github.com/mattn/goveralls

script:
- go test -v -covermode=count -coverprofile=coverage.out ./...

cache:
  directories:
  - $GOPATH
  - $HOME/google-cloud-sdk

after_success:
- $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci

deploy:
  provider: gae
  keyfile: .travis.gae-deploy.json
  skip_cleanup: true
  project: ip-spuf-ru
  version: master
  default: true
  on:
    branch: master
    go: 1.6.2
