sudo: false
language: go
go:
- 1.6.2
- tip

matrix:
  allow_failures:
  - go: tip

before_install:
- openssl aes-256-cbc -K $encrypted_1867c6df6d6e_key -iv $encrypted_1867c6df6d6e_iv -in .travis.tar.enc -out .travis.tar -d
- tar xvf .travis.tar
- go get -u golang.org/x/tools/cmd/cover
- go get -u github.com/mattn/goveralls

script:
- go test -v -covermode=count -coverprofile=coverage.out ./...

cache:
  directories:
  - $GOPATH

after_success:
- goveralls -coverprofile=coverage.out -service=travis-ci

deploy:
  provider: gae
  verbosity: info
  keyfile: .travis.gae-deploy.json
  skip_cleanup: true
  project: ip-spuf-ru
  version: master
  default: true
  on:
    branch: master
    go: 1.6.2
